version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-duplicati_server_1
      APP_PORT: 8200

  server:
    image: linuxserver/duplicati:2.0.8
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/backup:/backups
      - ${APP_DATA_DIR}/data/source:/source
      - ${UMBREL_ROOT}/data/storage:/umbrel-storage
